esphome:
  name: esp32s3_sensors
  friendly_name: ESP32S3 Test
  name_add_mac_suffix: false
  # # This will allow for (future) project identification,
  # # configuration and updates.
  # project:
  #   name: esphome.project-template
  #   version: "1.0"

esp32:
  board: esp32-s3-devkitm-1
  variant: esp32s3
  framework:
    type: esp-idf
    
external_components:
  - source:
      type: git
      url: https://gitee.com/zexuntec/inj_ip5209_esphome.git
    refresh: 0ms
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Set up a wifi access point
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:


api:
  reboot_timeout: 0s

ota:
  platform: esphome

web_server:
  port: 80
  # js_include: "./v2/www.js"
  # js_url: ""
  version: 3

logger:
  hardware_uart: UART0
  # hardware_uart: USB_SERIAL_JTAG
  baud_rate: 115200
  level: VERBOSE

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  skip_cert_cn_check: true
  username: !secret mqtt_user
  password: !secret mqtt_password
  clean_session: true
  publish_nan_as_none: true
  discovery: true
  discover_ip: true
  keepalive: 60s
  # topic_prefix: "homeassistant/living_room/sensors"
  discovery_unique_id_generator: mac
  discovery_prefix: "homeassistant"
  birth_message:
    topic: null
    payload: online
  will_message:
    topic: null
    payload: offline
  idf_send_async: false
  certificate_authority: !secret ssl_ca


# 配置I2C总线
i2c:
  - id: bus_a
    scl: GPIO13
    sda: GPIO12
    scan: true
    frequency: 400kHz
    # timeout: 1ms

text_sensor:
  - platform: version
    name: "ESPHome Version"

sensor:
  - platform: inj_ip5209
    i2c_id: bus_a
    irq_pin: GPIO7
    id: ip5209
    disable_auto_poweroff: true
    charge_current: 5
    battery_level:
      name: "Battery Level"
    battery_voltage:
      name: "Battery Voltage"
    current:
      name: "Battery Current"
    update_interval: 10s
